<?php

require_once('ukwa_dint_cf.inc');

function ukwa_dint_menu() {

  $items['lookup'] = array(
    'title' => 'Lookup a URL',
    'page callback' => 'ukwa_dint_ra_page',
    'access callback' => TRUE,
  );

  return $items;
}

// Previous method (still works) of generating a page by returning HTML
function ukwa_dint_html_page() {
  $output = '<p>A paragraph about some stuff...</p>';
  $output .= '<ul><li>first item</li><li>second item</li><li>third item</li></ul>';
  return $output;
}

// New method of generating the render array and returning that
function ukwa_dint_ra_page() {
  $params = drupal_get_query_parameters();
  if( array_key_exists('url', $params)) {
    $url = $params['url'];
  } else {
    $url = "";
  }

  $output =  array(
    'first_para' => array(
      '#type' => 'markup',
      '#markup' => '<p>A paragraph about some stuff...</p>'.$url,
    ),
    'second_para' => array(
      '#items' => array('first item', 'second item', 'third item'),
      '#theme' => 'item_list',
    ),
  );

  dpm(node_search_execute($url));

  return $output;
}
?>
